# Dataset
data_dir: data/glyph/
train_set: sans_trans.pkl
val_set: test_sans_trans.pkl
set_size: 1500
# Training config
epoch: 500
batch_size: 64
patience: 25
lr: 0.01
gamma: 0.1
step: 10
train: False
load_state: True
save: saved/
checkpoint: gcnn/sans_trans
# Model
model: gcnn
in_channels: 3
out_channels: 10
latent_dim: 2048