# Dataset
data_path: '../../dataset/PolygonsBenchmark/'
dataset:
  archae:
    train_file: archaeology_train_v8.npz
    test_file: archaeology_test_v8.npz
  building:
    train_file: buildings_train_v8.npz
    test_file: buildings_test_v8.npz
# Training Config
epoch: 100
batch_size: 128
lr: 0.01
step: 10
gamma: 0.1
patience: 25
save: ./saved/
# Model
in_channels: 5
out_channels: 10
