# dataset
data_dir: data/glyph/
train_set: sans_serif.pkl
val_set: test_sans_serif.pkl
set_size: 1500
# train config
epoch: 500
batch_size: 64
patience: 25
lr: 0.01
gamma: 0.1
step: 10
train: False
load_state: True
save: saved/
checkpoint: cnn/serif
# model
model: cnn 
in_channels: 3
out_channels: 10
latent_dim: 512 