# Dataset
data_folder: '../../dataset/LetterVectors/'
train_set: augmented_sans_serif.npz 
val_set: test_sans_serif.npz
embedding: 3000
# Training Config
epoch: 500
batch_size: 24
patience: 25
lr: 0.01
gamma: 0.1
step: 10
save: ./saved/
train: True
load_state: False
checkpoint: deepset/augmented_sans_serif_set
# Model
in_channels: 3
out_channels: 10
latent_space: 4096