# Dataset
data_path: '../../dataset/PolygonsBenchmark/'
# archae, building
dataset: archae
archae:
  train: archaeology_train_v8.npz
  test: archaeology_test_v8.npz
building:
  train: buildings_train_v8.npz
  test: buildings_test_v8.npz
# Training Config
epoch: 250
batch_size: 256
patience: 20
lr: 0.01
gamma: 0.1
step: 10
save: ./saved/
train: True
load_state: False
checkpoint: building_cnn_raw_geoms
# Model
in_channels: 5
out_channels: 10
