# Dataset
data_folder: '../../dataset/LetterVectors/'
train_set: train_augmented.npz
val_set: val_augmented.npz
# Training Config
epoch: 250
batch_size: 512
patience: 25
lr: 0.01
gamma: 0.1
step: 10
save: ./saved/
train: True
load_state: False
checkpoint: letter_vectors_cnn_augmented
# Model
in_channels: 2
out_channels: 26
